---
# tasks file for nginx
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

# tasks file for nginx
